import type { Json } from "@/types/database";
import type { AwarenessKind } from "@/domain/awareness";
export type ResourceRow = {
  id: string;
  legacy_id: string | null;
  kind: AwarenessKind;
  slug: string;
  title: string;
  summary: string;
  topic: string;
  language: "en" | "si" | "ta";
  status: "Published" | "Draft";
  display_order: number;
  featured: boolean;
  published_at: string | null;
  author: string;
  tags: string[];
  reading_minutes: number | null;
  content: Json;
  image_id: string | null;
  video_id: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
  version: number;
};
export type AssetRow = {
  id: string;
  resource_id: string | null;
  role: "image" | "video";
  bucket: string;
  path: string;
  file_name: string;
  mime_type: string;
  size_bytes: number;
  width: number;
  height: number;
  duration_seconds: number | null;
  alt_text: string;
  state: "pending" | "ready" | "active" | "retired";
  uploaded_by: string | null;
  created_at: string;
  updated_at: string;
};
export type AwarenessTable<T> = {
  Row: T;
  Insert: Partial<T>;
  Update: Partial<T>;
  Relationships: [];
};
